import type { Category, MenuItem, Order } from "@/types";

export const mockCategories: Category[] = [
  { id: "cat-1", name: "Burgers & Wraps", slug: "burgers-wraps", sortOrder: 1 },
  { id: "cat-2", name: "Pizzas",          slug: "pizzas",        sortOrder: 2 },
  { id: "cat-3", name: "Daily Snacks",    slug: "daily-snacks",  sortOrder: 3 },
  { id: "cat-4", name: "Beverages",       slug: "beverages",     sortOrder: 4 },
  { id: "cat-5", name: "Deals",           slug: "deals",         sortOrder: 5 },
];

const [burgers, pizzas, snacks, beverages, deals] = mockCategories;

export const mockMenuItems: MenuItem[] = [
  // ── Burgers & Wraps ─────────────────────────────────────────────
  {
    id: "item-1",
    slug: "classic-coop-burger",
    name: "Classic Coop Burger",
    description: "Crispy fried chicken fillet, fresh lettuce, tomato, and our secret coop sauce.",
    imageUrl: null,
    basePrice: 490,
    isAvailable: true,
    isFeatured: true,
    tags: ["bestseller"],
    sortOrder: 1,
    category: burgers,
    variants: [
      { id: "v1-1", name: "Single", priceExtra: 0,   isDefault: true },
      { id: "v1-2", name: "Double", priceExtra: 150, isDefault: false },
    ],
    addons: [
      { id: "a1-1", name: "Extra Cheese", price: 60, isAvailable: true },
      { id: "a1-2", name: "Jalapenos",    price: 40, isAvailable: true },
      { id: "a1-3", name: "Extra Sauce",  price: 30, isAvailable: true },
    ],
  },
  {
    id: "item-2",
    slug: "spicy-crunch-burger",
    name: "Spicy Crunch Burger",
    description: "Double-coated crispy chicken, spicy sriracha mayo, pickled slaw, and pepper jack cheese.",
    imageUrl: null,
    basePrice: 560,
    isAvailable: true,
    isFeatured: true,
    tags: ["spicy", "bestseller"],
    sortOrder: 2,
    category: burgers,
    variants: [
      { id: "v2-1", name: "Single", priceExtra: 0,   isDefault: true },
      { id: "v2-2", name: "Double", priceExtra: 150, isDefault: false },
    ],
    addons: [
      { id: "a2-1", name: "Extra Cheese", price: 60, isAvailable: true },
      { id: "a2-2", name: "Extra Patty",  price: 150, isAvailable: true },
    ],
  },
  {
    id: "item-3",
    slug: "zinger-wrap",
    name: "Zinger Wrap",
    description: "Hot zinger strip, coleslaw, and garlic mayo rolled in a warm tortilla.",
    imageUrl: null,
    basePrice: 420,
    isAvailable: true,
    isFeatured: false,
    tags: ["spicy"],
    sortOrder: 3,
    category: burgers,
    variants: [],
    addons: [
      { id: "a3-1", name: "Extra Sauce", price: 30, isAvailable: true },
    ],
  },
  {
    id: "item-4",
    slug: "coop-club-sandwich",
    name: "Coop Club Sandwich",
    description: "Triple-decker toasted sandwich with grilled chicken, egg, cheese, lettuce, and tomato.",
    imageUrl: null,
    basePrice: 530,
    isAvailable: true,
    isFeatured: false,
    tags: [],
    sortOrder: 4,
    category: burgers,
    variants: [],
    addons: [
      { id: "a4-1", name: "Extra Cheese", price: 60, isAvailable: true },
    ],
  },

  // ── Pizzas ───────────────────────────────────────────────────────
  {
    id: "item-5",
    slug: "bbq-chicken-pizza",
    name: "BBQ Chicken Pizza",
    description: "Smoky BBQ sauce base, tender chicken chunks, mozzarella, red onion, and bell peppers.",
    imageUrl: null,
    basePrice: 890,
    isAvailable: true,
    isFeatured: true,
    tags: ["bestseller"],
    sortOrder: 1,
    category: pizzas,
    variants: [
      { id: "v5-1", name: "Regular (9\")", priceExtra: 0,   isDefault: true },
      { id: "v5-2", name: "Large (12\")",  priceExtra: 300, isDefault: false },
    ],
    addons: [
      { id: "a5-1", name: "Extra Cheese",   price: 100, isAvailable: true },
      { id: "a5-2", name: "Extra Toppings", price: 80,  isAvailable: true },
    ],
  },
  {
    id: "item-6",
    slug: "loaded-fajita-pizza",
    name: "Loaded Fajita Pizza",
    description: "Spiced chicken fajita strips, capsicum, onion, sour cream drizzle on a thin crust.",
    imageUrl: null,
    basePrice: 950,
    isAvailable: true,
    isFeatured: false,
    tags: ["spicy"],
    sortOrder: 2,
    category: pizzas,
    variants: [
      { id: "v6-1", name: "Regular (9\")", priceExtra: 0,   isDefault: true },
      { id: "v6-2", name: "Large (12\")",  priceExtra: 300, isDefault: false },
    ],
    addons: [
      { id: "a6-1", name: "Extra Cheese", price: 100, isAvailable: true },
    ],
  },
  {
    id: "item-7",
    slug: "margherita-pizza",
    name: "Margherita Pizza",
    description: "Classic tomato sauce, fresh mozzarella, and basil on a golden crust.",
    imageUrl: null,
    basePrice: 750,
    isAvailable: true,
    isFeatured: false,
    tags: [],
    sortOrder: 3,
    category: pizzas,
    variants: [
      { id: "v7-1", name: "Regular (9\")", priceExtra: 0,   isDefault: true },
      { id: "v7-2", name: "Large (12\")",  priceExtra: 250, isDefault: false },
    ],
    addons: [
      { id: "a7-1", name: "Extra Cheese",    price: 100, isAvailable: true },
      { id: "a7-2", name: "Chicken Topping", price: 120, isAvailable: true },
    ],
  },

  // ── Daily Snacks ─────────────────────────────────────────────────
  {
    id: "item-8",
    slug: "coop-tenders-4pc",
    name: "Coop Tenders (4 pc)",
    description: "Four hand-battered crispy chicken tenders served with your choice of dipping sauce.",
    imageUrl: null,
    basePrice: 450,
    isAvailable: true,
    isFeatured: true,
    tags: ["bestseller"],
    sortOrder: 1,
    category: snacks,
    variants: [],
    addons: [
      { id: "a8-1", name: "BBQ Sauce",      price: 30, isAvailable: true },
      { id: "a8-2", name: "Garlic Mayo",    price: 30, isAvailable: true },
      { id: "a8-3", name: "Honey Mustard",  price: 30, isAvailable: true },
    ],
  },
  {
    id: "item-9",
    slug: "loaded-fries",
    name: "Loaded Fries",
    description: "Crispy golden fries topped with cheddar sauce, jalapenos, and crispy chicken bits.",
    imageUrl: null,
    basePrice: 380,
    isAvailable: true,
    isFeatured: false,
    tags: ["new"],
    sortOrder: 2,
    category: snacks,
    variants: [
      { id: "v9-1", name: "Regular", priceExtra: 0,  isDefault: true },
      { id: "v9-2", name: "Large",   priceExtra: 80, isDefault: false },
    ],
    addons: [
      { id: "a9-1", name: "Extra Cheese Sauce", price: 60, isAvailable: true },
    ],
  },
  {
    id: "item-10",
    slug: "chicken-nuggets-6pc",
    name: "Chicken Nuggets (6 pc)",
    description: "Six juicy all-white-meat nuggets with a perfectly crispy coating.",
    imageUrl: null,
    basePrice: 350,
    isAvailable: true,
    isFeatured: false,
    tags: [],
    sortOrder: 3,
    category: snacks,
    variants: [],
    addons: [
      { id: "a10-1", name: "Ketchup",     price: 0,  isAvailable: true },
      { id: "a10-2", name: "Garlic Mayo", price: 30, isAvailable: true },
    ],
  },

  // ── Beverages ────────────────────────────────────────────────────
  {
    id: "item-11",
    slug: "classic-milkshake",
    name: "Classic Milkshake",
    description: "Thick and creamy hand-blended milkshake. Choose from chocolate, vanilla, or strawberry.",
    imageUrl: null,
    basePrice: 290,
    isAvailable: true,
    isFeatured: false,
    tags: [],
    sortOrder: 1,
    category: beverages,
    variants: [
      { id: "v11-1", name: "Chocolate",  priceExtra: 0,  isDefault: true },
      { id: "v11-2", name: "Vanilla",    priceExtra: 0,  isDefault: false },
      { id: "v11-3", name: "Strawberry", priceExtra: 0,  isDefault: false },
    ],
    addons: [],
  },
  {
    id: "item-12",
    slug: "soft-drink",
    name: "Soft Drink",
    description: "Chilled Pepsi, 7UP, or Mountain Dew.",
    imageUrl: null,
    basePrice: 120,
    isAvailable: true,
    isFeatured: false,
    tags: ["value"],
    sortOrder: 2,
    category: beverages,
    variants: [
      { id: "v12-1", name: "Regular (330ml)", priceExtra: 0,  isDefault: true },
      { id: "v12-2", name: "Large (500ml)",   priceExtra: 50, isDefault: false },
    ],
    addons: [],
  },

  // ── Deals ────────────────────────────────────────────────────────
  {
    id: "item-13",
    slug: "family-feast-deal",
    name: "Family Feast Deal",
    description: "2 Classic Coop Burgers + 1 Large BBQ Pizza + Loaded Fries + 4 Soft Drinks. Perfect for 4.",
    imageUrl: null,
    basePrice: 2490,
    isAvailable: true,
    isFeatured: true,
    tags: ["bestseller", "value"],
    sortOrder: 1,
    category: deals,
    variants: [],
    addons: [],
  },
  {
    id: "item-14",
    slug: "coop-combo",
    name: "Coop Combo",
    description: "Any burger + Loaded Fries + Soft Drink. Mix and match your favourites.",
    imageUrl: null,
    basePrice: 850,
    isAvailable: true,
    isFeatured: false,
    tags: ["value"],
    sortOrder: 2,
    category: deals,
    variants: [
      { id: "v14-1", name: "With Classic Burger", priceExtra: 0,   isDefault: true },
      { id: "v14-2", name: "With Spicy Burger",   priceExtra: 70,  isDefault: false },
      { id: "v14-3", name: "With Zinger Wrap",    priceExtra: -40, isDefault: false },
    ],
    addons: [
      { id: "a14-1", name: "Upgrade to Large Fries", price: 80, isAvailable: true },
    ],
  },
];

export const mockOrders: Order[] = [
  {
    id: "mock-order-1",
    orderNumber: "CC-240001",
    status: "DELIVERED",
    fulfillmentType: "DELIVERY",
    subtotal: 1440,
    deliveryFee: 0,
    total: 1440,
    paymentMethod: "CASH_ON_DELIVERY",
    customerName: "Ali Khan",
    customerPhone: "03001234567",
    notes: null,
    address: { line1: "House 12, Street 5", area: "DHA Phase 1", city: "Lahore" },
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
    items: [
      {
        id: "oi-1",
        menuItemId: "item-1",
        variantId: "v1-1",
        quantity: 2,
        unitPrice: 490,
        totalPrice: 980,
        addons: [{ name: "Extra Cheese", price: 60 }],
        menuItem: { name: "Classic Coop Burger" },
        variant: { name: "Single" },
      },
      {
        id: "oi-2",
        menuItemId: "item-9",
        variantId: "v9-2",
        quantity: 1,
        unitPrice: 460,
        totalPrice: 460,
        addons: [],
        menuItem: { name: "Loaded Fries" },
        variant: { name: "Large" },
      },
    ],
  },
  {
    id: "mock-order-2",
    orderNumber: "CC-240002",
    status: "PREPARING",
    fulfillmentType: "PICKUP",
    subtotal: 950,
    deliveryFee: 0,
    total: 950,
    paymentMethod: "CASH_ON_DELIVERY",
    customerName: "Sara Ahmed",
    customerPhone: "03111234567",
    notes: "Extra spicy please",
    address: null,
    createdAt: new Date(Date.now() - 30 * 60 * 1000).toISOString(),
    items: [
      {
        id: "oi-3",
        menuItemId: "item-6",
        variantId: "v6-1",
        quantity: 1,
        unitPrice: 950,
        totalPrice: 950,
        addons: [],
        menuItem: { name: "Loaded Fajita Pizza" },
        variant: { name: "Regular (9\")" },
      },
    ],
  },
];
